name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Run rustfmt to check code formatting
    - name: Check formatting
      run: rustfmt --check $(find . -name "*.rs")
    - name: Check linting
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Tests
      run: cargo test --all
